[workspace]
members = [
  "m328p-sensors",
  "m2560-oled-shields"
]
exclude = [
  "avr-hal",
  "embedded-sdmmc",
]

[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"