[build]
target = "spec/avr-atmega328p.json"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mangled-names"]

[target. 'cfg(target_arch = "avr")']
runner = "ravedude uno --open-console --baudrate 57600"