[build]
target = "spec/avr-atmega2560.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno -cb 57600"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mangled-names"]

[target. 'cfg(target_arch = "avr")']
runner = "ravedude uno --open-console --baudrate 57600"