[alias]
build-sensors = "build --verbose --package m328p-sensors --target=m328p-sensors/spec/avr-atmega328p.json"
build-i2c = "build --verbose --package m328p-i2c-displays --target=m328p-i2c-displays/spec/avr-atmega328p.json"

[unstable]
build-std = ["core"]
