[package]
name = "m328p-sensors"
version = "0.1.0"

[dependencies]
panic-halt = "0.2.0"
embedded-hal = "0.2.3"
nb = "1.0.0"
ufmt = "0.1.0"

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "92d540c"
features = ["arduino-uno"]

