name: Rust

on:
  push:
    branches: [ alpha0.0.1 ]
  pull_request:
    branches: [ alpha0.0.1 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build-328p && cargo build-2560
    - name: Run tests
      run: cargo test --verbose
